language: minimal

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - PROJECT=pearbuild
    - DOCKER_COMPOSE_VERSION=1.24.1
    - PACKAGE_VCS_URL=https://github.com/aursu/rpmbuild-php-geoip
  jobs:
    - PHP=php71 OS=centos7
    - PHP=php71 OS=centos8
    - PHP=php73 OS=centos7
    - PHP=php73 OS=centos8

before_install:
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - |
    export REPOSERVICE=${OS}repo
    docker-compose -f rpmbuild/docker-compose.yml pull ${REPOSERVICE} webrepo

install:
  - |
    export REPOSERVICE=${OS}repo
    docker-compose -f rpmbuild/docker-compose.yml up -d ${REPOSERVICE} webrepo

before_script:
  - |
    export BUILD_COMPOSE_FILE=docker-compose.${PHP}.yml
    export BUILDSERVICE=${OS}${PROJECT}${PHP}${BUILD}
    docker-compose -f ${BUILD_COMPOSE_FILE} build --no-cache ${BUILDSERVICE}

script:
  - |
    export BUILD_COMPOSE_FILE=docker-compose.${PHP}.yml
    export BUILDSERVICE=${OS}${PROJECT}${PHP}
    docker-compose -f ${BUILD_COMPOSE_FILE} up ${BUILDSERVICE}

before_deploy:
  - |
    export UPLOADER=${OS}bintray
    docker-compose -f rpmbuild/docker-compose.bintray.yml pull ${UPLOADER}

deploy:
  provider: script
  script: |
    export BINTRAY_REPO=${PHP}custom
    export UPLOADER=${OS}bintray
    docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL ${UPLOADER}
  on:
    all_branches: true

jobs:
  include:
    - stage: test
    - stage: test
      before_script:
        - |
          export BUILD_COMPOSE_FILE=docker-compose.${PHP}.yml
          export BUILDSERVICE=${OS}${PROJECT}${PHP}rel
          docker-compose -f ${BUILD_COMPOSE_FILE} build --no-cache ${BUILDSERVICE}
      script:
        - |
          export BUILD_COMPOSE_FILE=docker-compose.${PHP}.yml
          export BUILDSERVICE=${OS}${PROJECT}${PHP}rel
          docker-compose -f ${BUILD_COMPOSE_FILE} up ${BUILDSERVICE}