language: minimal

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - PACKAGE_VCS_URL=https://github.com/aursu/rpmbuild-php-pear
  jobs:
    - BUILD_COMPOSE_FILE=docker-compose.yml       BINTRAY_REPO=php71custom BUILD=centos7pearbuildphp7     UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.yml       BINTRAY_REPO=php71custom BUILD=centos7pearbuildphp7rel  UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.yml       BINTRAY_REPO=php71custom BUILD=centos8pearbuildphp7     UPLOADER=centos8bintray
    - BUILD_COMPOSE_FILE=docker-compose.yml       BINTRAY_REPO=php71custom BUILD=centos8pearbuildphp7rel  UPLOADER=centos8bintray
    - BUILD_COMPOSE_FILE=docker-compose.php73.yml BINTRAY_REPO=php73custom BUILD=centos7pearbuildphp73    UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.php73.yml BINTRAY_REPO=php73custom BUILD=centos7pearbuildphp73rel UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.php73.yml BINTRAY_REPO=php73custom BUILD=centos8pearbuildphp73    UPLOADER=centos8bintray
    - BUILD_COMPOSE_FILE=docker-compose.php73.yml BINTRAY_REPO=php73custom BUILD=centos8pearbuildphp73rel UPLOADER=centos8bintray
    - BUILD_COMPOSE_FILE=docker-compose.php74.yml BINTRAY_REPO=php74custom BUILD=centos7pearbuildphp74    UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.php74.yml BINTRAY_REPO=php74custom BUILD=centos8pearbuildphp74    UPLOADER=centos8bintray

install: skip

before_script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} build --no-cache ${BUILD}

script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} up ${BUILD}

before_deploy:
  - docker-compose -f rpmbuild/docker-compose.bintray.yml pull ${UPLOADER}

deploy:
  provider: script
  script: docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL ${UPLOADER}
  on:
    all_branches: true

jobs:
  include:
    - stage: docker
      before_install:
        - docker-compose -f rpmbuild/docker-compose.yml pull  centos7repo centos8repo webrepo
      install:
        - docker-compose -f rpmbuild/docker-compose.yml up -d centos7repo centos8repo webrepo
      script:
        - docker-compose -f build/php71/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/php71/docker-compose.yml push
        on:
          all_branches: true
    - stage: docker
      before_install:
        - docker-compose -f rpmbuild/docker-compose.yml pull  centos7repo centos8repo webrepo
      install:
        - docker-compose -f rpmbuild/docker-compose.yml up -d  centos7repo centos8repo webrepo
      script:
        - docker-compose -f build/php73/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/php73/docker-compose.yml push
        on:
          all_branches: true
    - stage: docker
      before_install:
        - docker-compose -f rpmbuild/docker-compose.yml pull  centos7repo centos8repo webrepo
      install:
        - docker-compose -f rpmbuild/docker-compose.yml up -d  centos7repo centos8repo webrepo
      script:
        - docker-compose -f build/php74/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/php74/docker-compose.yml push
        on:
          all_branches: true