version: "3.5"
services:
  centos7pearbuildphp7:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
  centos7pearbuildphp7rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        image: build-rel

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
