version: "3.5"
services:
  centos7pearbuildphp7:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        dockerfile: Dockerfile.php73
        centos: 7.8.2003
        buildrepo: php7build
  centos7pearbuildphp7rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        dockerfile: Dockerfile.php73
        centos: 7.8.2003
        buildrepo: php7build
        image: build-rel
  centos8pearbuildphp7:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        dockerfile: Dockerfile.php73
        centos: 8.2.2004
        buildrepo: php7build
  centos8pearbuildphp7rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        dockerfile: Dockerfile.php73
        centos: 8.2.2004
        buildrepo: php7build
        image: build-rel

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
  rpm8:
    name: rpm8
