version: "3.5"
services:
  centos6pearbuildphp7:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: 6
    image: aursu/php7build:6-pear
  centos6pearbuildphp7rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: 6
        image: build-rel
    image: aursu/php7build:6-pear-rel
  centos7pearbuildphp7:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
    image: aursu/php7build:7-pear
  centos7pearbuildphp7rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        image: build-rel
    image: aursu/php7build:7-pear-rel

volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
