version: "3.5"
services:
  centos6pearbuildphp7:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: 6/php/7.1/Dockerfile
    image: aursu/pearbuild:6-php71
  centos7pearbuildphp7:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: 7/php/7.1/Dockerfile
    image: aursu/pearbuild:7-php71
  centos7pearbuildphp7rel:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: 7/php/7.1/Dockerfile.rel
    image: aursu/pearbuild:7-php71-rel

volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
