version: "3.5"
services:
  centos7pearbuildphp80:
    entrypoint: ["/usr/bin/rpmbuild", "php8-pear.spec"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
        buildrepo: php80build
  centos8pearbuildphp80:
    entrypoint: ["/usr/bin/rpmbuild", "php8-pear.spec"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS8
        buildrepo: php80build

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
  rpm8:
    name: rpm8