version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Start docker services for rpmbuild
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
            docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - run:
          name: Build PHP-PEAR Docker images
          command: docker-compose build --no-cache --pull
      - run:
          name: Build PHP-PEAR RPM packages
          command: docker-compose up
      - run:
          name: Copy RPM packages
          command: |
            rm -rf ~/el6 ~/el7
            mkdir -p ~/el6 ~/el7
            docker cp rpmbuild_webrepo_1:/home/centos-6/rpmbuild/RPMS ~/el6/
            docker cp rpmbuild_webrepo_1:/home/centos-7/rpmbuild/RPMS ~/el7/
            rm -rf ~/el*/RPMS/repodata
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
      - run:
          name: Build PHP-PEAR Dcoker build images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            sleep 30
            docker-compose -f build/docker-compose.yml build --no-cache --pull
            docker push aursu/pearbuild:7-build
            docker push aursu/pearbuild:7-build-rel
            docker push aursu/pearbuild:6-build
            docker push aursu/pearbuild:6-build-rel
      - store_artifacts:
          path: ~/el6/RPMS
      - store_artifacts:
          path: ~/el7/RPMS
  build5:
    machine:
      docker_layer_caching: true
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Start docker services for rpmbuild
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
            docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - run:
          name: Build PHP-PEAR Docker images
          command: docker-compose -f docker-compose.php5.yml build --no-cache --pull
      - run:
          name: Build PHP-PEAR RPM packages
          command: docker-compose -f docker-compose.php5.yml up
      - run:
          name: Copy RPM packages
          command: |
            rm -rf ~/php5
            mkdir -p ~/php5/el6 ~/php5/el7
            docker cp rpmbuild_webrepo_1:/home/centos-6/rpmbuild/RPMS ~/php5/el6/
            docker cp rpmbuild_webrepo_1:/home/centos-7/rpmbuild/RPMS ~/php5/el7/
            rm -rf ~/php5/*/RPMS/repodata
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos6bintray
      - run:
          name: Build PHP-PEAR Docker build images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            sleep 30
            docker-compose -f build/docker-compose.php5.yml build --no-cache --pull
            docker push aursu/pearbuild:7-build-php5
            docker push aursu/pearbuild:6-build-php5
      - store_artifacts:
          path: ~/php5
workflows:
  version: 2
  pearbuild:
    jobs:
      - build5
      - build
