version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.0

workflows:
  pearbuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7pearbuildphp7rpm
          build_service: centos7pearbuildphp7
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos7pearbuildphp7relrpm
          build_service: centos7pearbuildphp7rel
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8pearbuildphp7rpm
          build_service: centos8pearbuildphp7
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos8pearbuildphp7rel
          build_service: centos8pearbuildphp7rel
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7pearbuildphp73rpm
          build_file: docker-compose.php73.yml
          build_service: centos7pearbuildphp73
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos7pearbuildphp73relrpm
          build_file: docker-compose.php73.yml
          build_service: centos7pearbuildphp73rel
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8pearbuildphp73rpm
          build_file: docker-compose.php73.yml
          build_service: centos8pearbuildphp73
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos8pearbuildphp73relrpm
          build_file: docker-compose.php73.yml
          build_service: centos8pearbuildphp73rel
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7pearbuildphp74rpm
          build_file: docker-compose.php74.yml
          build_service: centos7pearbuildphp74
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8pearbuildphp74rpm
          build_file: docker-compose.php74.yml
          build_service: centos8pearbuildphp74
          bintray_uploader: centos8bintray
      - docker-rpmbuild/image:
          name: centos7pearbuildphp7
          compose_file: build/php71/docker-compose.yml
          build_service: centos7pearbuildphp7
          requires:
            - centos7pearbuildphp7rpm
      - docker-rpmbuild/image:
          name: centos7pearbuildphp7rel
          compose_file: build/php71/docker-compose.yml
          build_service: centos7pearbuildphp7rel
          requires:
            - centos7pearbuildphp7relrpm
      - docker-rpmbuild/image:
          name: centos8pearbuildphp7
          compose_file: build/php71/docker-compose.yml
          build_service: centos8pearbuildphp7
          requires:
            - centos8pearbuildphp7rpm
      - docker-rpmbuild/image:
          name: centos8pearbuildphp7rel
          compose_file: build/php71/docker-compose.yml
          build_service: centos8pearbuildphp7rel
          requires:
            - centos8pearbuildphp7relrpm
      - docker-rpmbuild/image:
          name: centos7pearbuildphp73
          compose_file: build/php73/docker-compose.yml
          build_service: centos7pearbuildphp73
          requires:
            - centos7pearbuildphp73rpm
      - docker-rpmbuild/image:
          name: centos7pearbuildphp73rel
          compose_file: build/php73/docker-compose.yml
          build_service: centos7pearbuildphp73rel
          requires:
            - centos7pearbuildphp73relrpm
      - docker-rpmbuild/image:
          name: centos8pearbuildphp73
          compose_file: build/php73/docker-compose.yml
          build_service: centos8pearbuildphp73
          requires:
            - centos8pearbuildphp73rpm
      - docker-rpmbuild/image:
          name: centos8pearbuildphp73rel
          compose_file: build/php73/docker-compose.yml
          build_service: centos8pearbuildphp73rel
          requires:
            - centos8pearbuildphp73relrpm
      - docker-rpmbuild/image:
          name: centos7pearbuildphp74
          compose_file: build/php74/docker-compose.yml
          build_service: centos7pearbuildphp74
          requires:
            - centos7pearbuildphp74rpm
      - docker-rpmbuild/image:
          name: centos8pearbuildphp74
          compose_file: build/php74/docker-compose.yml
          build_service: centos8pearbuildphp74
          requires:
            - centos8pearbuildphp74rpm