version: 2
jobs:
  build71:
    machine:
      docker_layer_caching: true
    environment:
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-pear
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Pull images for RPM build docker services
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
      - run:
          name: Start docker services for rpmbuild
          command: |
            docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - run:
          name: Build PHP-PEAR Docker images
          command: docker-compose build --no-cache --pull
      - run:
          name: Build PHP-PEAR RPM packages
          command: docker-compose up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=custom \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=custom \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos6bintray
      - run:
          name: Build PHP-PEAR Dcoker build images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            sleep 30
            docker-compose -f build/docker-compose.yml build --no-cache --pull
            docker push aursu/pearbuild:7-php-7.1
            docker push aursu/pearbuild:7-php7-7.1
            docker push aursu/pearbuild:6-php-7.1
            docker push aursu/pearbuild:6-php7-7.1
  build5:
    machine:
      docker_layer_caching: true
    environment:
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-pear
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Pull images for RPM build docker services
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
      - run:
          name: Start docker services for rpmbuild
          command: |
            docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - run:
          name: Build PHP-PEAR Docker images
          command: docker-compose -f docker-compose.php5.yml build --no-cache --pull
      - run:
          name: Build PHP-PEAR RPM packages
          command: docker-compose -f docker-compose.php5.yml up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=php5custom \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=php5custom \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos6bintray
      - run:
          name: Build PHP-PEAR Docker build images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            sleep 30
            docker-compose -f build/docker-compose.php5.yml build --no-cache --pull
            docker push aursu/pearbuild:7-php-5.6
            docker push aursu/pearbuild:6-php-5.6
  build73:
    machine:
      docker_layer_caching: true
    environment:
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-pear
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Pull images for RPM build docker services
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
      - run:
          name: Start docker services for rpmbuild
          command: |
            docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - run:
          name: Build PHP-PEAR Docker images
          command: docker-compose -f docker-compose.php73.yml build --no-cache --pull
      - run:
          name: Build PHP-PEAR RPM packages
          command: docker-compose -f docker-compose.php73.yml up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=php73custom \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos7bintray
      - run:
          name: Build PHP-PEAR Docker build images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            sleep 30
            docker-compose -f build/docker-compose.php73.yml build --no-cache --pull
            docker push aursu/pearbuild:7-php-7.3
            docker push aursu/pearbuild:7-php7-7.3

workflows:
  version: 2
  pearbuild:
    jobs:
      - build5
      - build71
      - build73
